### ISSUE TITLE
Crashes when loading the game

### ISSUE THREAD

**Issue by Arthur-The-Ok** [WMF-Industries/ExpandedIndustries#11]
arc.util.ArcRuntimeException: java.lang.NullPointerException
	at arc.assets.AssetManager.handleTaskError(AssetManager.java:669)
	at arc.assets.AssetManager.update(AssetManager.java:441)
	at arc.assets.AssetManager.update(AssetManager.java:464)
	at mindustry.ClientLauncher.update(ClientLauncher.java:208)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: java.lang.NullPointerException
	at ExpandedIndustries.content.EITechTree.node(EITechTree.java:24)
	at ExpandedIndustries.content.EITechTree.lambda$load$46(EITechTree.java:179)
	at ExpandedIndustries.content.EITechTree.mergeNode(EITechTree.java:20)
	at ExpandedIndustries.content.EITechTree.load(EITechTree.java:178)
	at ExpandedIndustries.ExpandedIndustries.loadAllContent(ExpandedIndustries.java:31)
	at ExpandedIndustries.ExpandedIndustries.loadContent(ExpandedIndustries.java:16)
	at mindustry.mod.Mods.loadContent(Mods.java:653)
	at mindustry.core.ContentLoader.createModContent(ContentLoader.java:61)
	at mindustry.ClientLauncher.lambda$setup$4(ClientLauncher.java:162)
	at arc.assets.AssetManager$1.loadSync(AssetManager.java:333)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:108)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:73)
	at arc.assets.AssetManager.updateTask(AssetManager.java:590)
	at arc.assets.AssetManager.update(AssetManager.java:439)
	... 6 more

**Comment by WMF-Industries** [comment]
known issue, fixed with the newest build

**Comment by Arthur-The-Ok** [comment]
> known issue, fixed with the newest build

But I'm using the latest build (1.5 B5) and it still crashes

**Comment by WMF-Industries** [comment]
> > known issue, fixed with the newest build
> 
> But I'm using the latest build (1.5 B5) and it still crashes

please update it once again, the recent temporary fix should eliminate the issue with it crashing

**Comment by Arthur-The-Ok** [comment]
I was about to type that now it worked, the problem was that I was still using the version on the "releases" section

**Comment by WMF-Industries** [comment]
i updated this release too, if you find any other issues, tell me - I'm planning to fix most of them and rebalance stuff soon
